"""Alert Queue — filterable alert triage view."""

from __future__ import annotations

import plotly.express as px
import streamlit as st

from aml_framework.dashboard.components import page_header

page_header(
    "Alert Queue",
    "Triage and prioritize alerts generated by the detection engine.",
)

spec = st.session_state.spec
df_alerts = st.session_state.df_alerts

if st.session_state.get("guided_demo"):
    st.info(
        "**Guided Demo — Alert Queue**\n\n"
        "This is the L1 analyst's work queue. Each alert is generated by "
        "a spec-driven rule and includes the customer, aggregated amounts, "
        "and time window. Filter by rule or severity to focus your review."
    )

if df_alerts.empty:
    st.warning("No alerts in this run.")
    st.stop()

# --- Filters ---
col_f1, col_f2 = st.columns(2)
with col_f1:
    rule_options = sorted(df_alerts["rule_id"].unique())
    selected_rules = st.multiselect("Filter by rule", rule_options, default=rule_options)
with col_f2:
    sev_map = {r.id: r.severity for r in spec.rules}
    severities = sorted(set(sev_map.values()))
    selected_sev = st.multiselect("Filter by severity", severities, default=severities)

# Apply filters.
filtered = df_alerts[df_alerts["rule_id"].isin(selected_rules)]
filtered = filtered[filtered["rule_id"].map(sev_map).isin(selected_sev)]

# Add severity column for display.
display_df = filtered.copy()
display_df["severity"] = display_df["rule_id"].map(sev_map)

# --- Alert Table ---
st.subheader(f"Alerts ({len(display_df)})")
show_cols = ["rule_id", "severity"]
if "customer_id" in display_df.columns:
    show_cols.append("customer_id")
if "sum_amount" in display_df.columns:
    show_cols.append("sum_amount")
if "count" in display_df.columns:
    show_cols.append("count")
if "window_start" in display_df.columns:
    show_cols.extend(["window_start", "window_end"])

available = [c for c in show_cols if c in display_df.columns]
st.dataframe(display_df[available], use_container_width=True, hide_index=True)

st.divider()

# --- Charts ---
col_left, col_right = st.columns(2)
with col_left:
    st.subheader("Alert Volume by Rule")
    chart = display_df.groupby("rule_id").size().reset_index(name="count")
    chart["severity"] = chart["rule_id"].map(sev_map)
    color_map = {"high": "#ef4444", "medium": "#f59e0b", "low": "#22c55e", "critical": "#7c3aed"}
    fig = px.bar(
        chart, x="rule_id", y="count", color="severity",
        color_discrete_map=color_map,
        labels={"rule_id": "Rule", "count": "Alerts"},
    )
    fig.update_layout(height=350, margin=dict(t=10))
    st.plotly_chart(fig, use_container_width=True)

with col_right:
    st.subheader("Severity Distribution")
    sev_counts = display_df["severity"].value_counts().reset_index()
    sev_counts.columns = ["severity", "count"]
    fig = px.pie(
        sev_counts, names="severity", values="count",
        color="severity", color_discrete_map=color_map,
    )
    fig.update_layout(height=350, margin=dict(t=10))
    st.plotly_chart(fig, use_container_width=True)
