"""Alert Queue -- filterable alert triage view."""

from __future__ import annotations

import plotly.express as px
import streamlit as st

from aml_framework.dashboard.components import SEVERITY_COLORS, chart_layout, kpi_card, page_header

page_header(
    "Alert Queue",
    "Triage and prioritize alerts generated by the detection engine.",
)

spec = st.session_state.spec
df_alerts = st.session_state.df_alerts

if st.session_state.get("guided_demo"):
    st.info(
        "**Guided Demo -- Alert Queue**\n\n"
        "This is the L1 analyst's work queue. Each alert is generated by "
        "a spec-driven rule. Filter by rule or severity to focus your review."
    )

if df_alerts.empty:
    st.warning("No alerts in this run.")
    st.stop()

# --- Summary KPIs ---
sev_map = {r.id: r.severity for r in spec.rules}
c1, c2, c3, c4 = st.columns(4)
with c1:
    kpi_card("Total Alerts", len(df_alerts), "#2563eb")
with c2:
    high_ct = sum(1 for _, r in df_alerts.iterrows() if sev_map.get(r["rule_id"]) == "high")
    kpi_card("High Severity", high_ct, "#dc2626")
with c3:
    kpi_card("Rules Triggered", df_alerts["rule_id"].nunique(), "#7c3aed")
with c4:
    if "customer_id" in df_alerts.columns:
        kpi_card("Customers", df_alerts["customer_id"].nunique(), "#d97706")
    else:
        kpi_card("Customers", "N/A", "#6b7280")

st.markdown("<br>", unsafe_allow_html=True)

# --- Filters ---
col_f1, col_f2 = st.columns(2)
with col_f1:
    rule_options = sorted(df_alerts["rule_id"].unique())
    selected_rules = st.multiselect("Filter by rule", rule_options, default=rule_options)
with col_f2:
    severities = sorted(set(sev_map.values()))
    selected_sev = st.multiselect("Filter by severity", severities, default=severities)

filtered = df_alerts[df_alerts["rule_id"].isin(selected_rules)]
filtered = filtered[filtered["rule_id"].map(sev_map).isin(selected_sev)]
display_df = filtered.copy()
display_df["severity"] = display_df["rule_id"].map(sev_map)

# --- Alert Table ---
st.markdown(f"### Alerts ({len(display_df)})")
show_cols = ["rule_id", "severity"]
for c in ["customer_id", "sum_amount", "count", "window_start", "window_end"]:
    if c in display_df.columns:
        show_cols.append(c)
available = [c for c in show_cols if c in display_df.columns]

def _highlight_severity(val: str) -> str:
    color = SEVERITY_COLORS.get(val, "")
    if color:
        return f"color: {color}; font-weight: 700;"
    return ""

styled = display_df[available].style.map(_highlight_severity, subset=["severity"])
st.dataframe(styled, use_container_width=True, hide_index=True, height=400)

st.markdown("<br>", unsafe_allow_html=True)

# --- Charts ---
col_left, col_right = st.columns(2)
with col_left:
    st.markdown("### Alert Volume by Rule")
    chart = display_df.groupby("rule_id").size().reset_index(name="count")
    chart["severity"] = chart["rule_id"].map(sev_map)
    chart = chart.sort_values("count", ascending=True)
    fig = px.bar(
        chart, y="rule_id", x="count", color="severity",
        orientation="h",
        color_discrete_map=SEVERITY_COLORS,
        labels={"rule_id": "", "count": "Alerts"},
    )
    fig.update_layout(yaxis_title="", showlegend=False)
    st.plotly_chart(chart_layout(fig, 320), use_container_width=True)

with col_right:
    st.markdown("### Severity Distribution")
    sev_counts = display_df["severity"].value_counts().reset_index()
    sev_counts.columns = ["severity", "count"]
    fig = px.pie(
        sev_counts, names="severity", values="count",
        color="severity", color_discrete_map=SEVERITY_COLORS,
        hole=0.45,
    )
    fig.update_traces(textposition="inside", textinfo="percent+label")
    st.plotly_chart(chart_layout(fig, 320), use_container_width=True)
