"""Alert Queue -- filterable alert triage view."""

from __future__ import annotations

import plotly.express as px
import streamlit as st

from aml_framework.dashboard.components import SEVERITY_COLORS, chart_layout, kpi_card, page_header
from aml_framework.dashboard.audience import show_audience_context


def _bulk_action(case_ids: list[str], event: str, disposition: str) -> None:
    """Apply an action to multiple cases at once."""
    import json
    from datetime import datetime, timezone
    from pathlib import Path

    run_dir = st.session_state.run_dir
    decisions_path = Path(run_dir) / "decisions.jsonl"
    ts = datetime.now(tz=timezone.utc).isoformat()
    count = 0
    for cid in case_ids:
        decision = {
            "ts": ts,
            "event": event,
            "case_id": cid,
            "disposition": disposition,
            "source": "bulk_action",
        }
        with decisions_path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(decision, sort_keys=True, separators=(",", ":")) + "\n")
        # Update session state.
        if "df_cases" in st.session_state and not st.session_state.df_cases.empty:
            mask = st.session_state.df_cases["case_id"] == cid
            if mask.any():
                st.session_state.df_cases.loc[mask, "status"] = disposition
        count += 1
    st.success(f"Bulk {event}: {count} cases -> {disposition}")


page_header(
    "Alert Queue",
    "Triage and prioritize alerts generated by the detection engine.",
)
show_audience_context("Alert Queue")

spec = st.session_state.spec
df_alerts = st.session_state.df_alerts

if st.session_state.get("guided_demo"):
    st.info(
        "**Guided Demo -- Alert Queue**\n\n"
        "This is the L1 analyst's work queue. Each alert is generated by "
        "a spec-driven rule. Filter by rule or severity to focus your review."
    )

if df_alerts.empty:
    st.warning("No alerts in this run.")
    st.stop()

# --- Summary KPIs ---
sev_map = {r.id: r.severity for r in spec.rules}
c1, c2, c3, c4 = st.columns(4)
with c1:
    kpi_card("Total Alerts", len(df_alerts), "#2563eb")
with c2:
    high_ct = sum(1 for _, r in df_alerts.iterrows() if sev_map.get(r["rule_id"]) == "high")
    kpi_card("High Severity", high_ct, "#dc2626")
with c3:
    kpi_card("Rules Triggered", df_alerts["rule_id"].nunique(), "#7c3aed")
with c4:
    if "customer_id" in df_alerts.columns:
        kpi_card("Customers", df_alerts["customer_id"].nunique(), "#d97706")
    else:
        kpi_card("Customers", "N/A", "#6b7280")

st.markdown("<br>", unsafe_allow_html=True)

# --- Filters ---
col_f1, col_f2 = st.columns(2)
with col_f1:
    rule_options = sorted(df_alerts["rule_id"].unique())
    selected_rules = st.multiselect("Filter by rule", rule_options, default=rule_options)
with col_f2:
    severities = sorted(set(sev_map.values()))
    selected_sev = st.multiselect("Filter by severity", severities, default=severities)

filtered = df_alerts[df_alerts["rule_id"].isin(selected_rules)]
filtered = filtered[filtered["rule_id"].map(sev_map).isin(selected_sev)]
display_df = filtered.copy()
display_df["severity"] = display_df["rule_id"].map(sev_map)

# --- Alert Table ---
col_title, col_download = st.columns([3, 1])
col_title.markdown(f"### Alerts ({len(display_df)})")
csv_data = display_df[
    [
        c
        for c in [
            "rule_id",
            "severity",
            "customer_id",
            "sum_amount",
            "count",
            "window_start",
            "window_end",
        ]
        if c in display_df.columns
    ]
].to_csv(index=False)
col_download.download_button(
    "Export CSV",
    csv_data,
    "alerts.csv",
    "text/csv",
    use_container_width=True,
)
show_cols = ["rule_id", "severity"]
for c in ["customer_id", "sum_amount", "count", "window_start", "window_end"]:
    if c in display_df.columns:
        show_cols.append(c)
available = [c for c in show_cols if c in display_df.columns]


def _highlight_severity(val: str) -> str:
    color = SEVERITY_COLORS.get(val, "")
    if color:
        return f"color: {color}; font-weight: 700;"
    return ""


styled = display_df[available].style.map(_highlight_severity, subset=["severity"])
st.dataframe(styled, use_container_width=True, hide_index=True, height=400)

st.markdown("<br>", unsafe_allow_html=True)

# --- Charts ---
col_left, col_right = st.columns(2)
with col_left:
    st.markdown("### Alert Volume by Rule")
    chart = display_df.groupby("rule_id").size().reset_index(name="count")
    chart["severity"] = chart["rule_id"].map(sev_map)
    chart = chart.sort_values("count", ascending=True)
    fig = px.bar(
        chart,
        y="rule_id",
        x="count",
        color="severity",
        orientation="h",
        color_discrete_map=SEVERITY_COLORS,
        labels={"rule_id": "", "count": "Alerts"},
    )
    fig.update_layout(yaxis_title="", showlegend=False)
    st.plotly_chart(chart_layout(fig, 320), use_container_width=True)

with col_right:
    st.markdown("### Severity Distribution")
    sev_counts = display_df["severity"].value_counts().reset_index()
    sev_counts.columns = ["severity", "count"]
    fig = px.pie(
        sev_counts,
        names="severity",
        values="count",
        color="severity",
        color_discrete_map=SEVERITY_COLORS,
        hole=0.45,
    )
    fig.update_traces(textposition="inside", textinfo="percent+label")
    st.plotly_chart(chart_layout(fig, 320), use_container_width=True)

# --- Case Queue (Analyst Inbox) ---
st.markdown("<br>", unsafe_allow_html=True)
st.markdown("### Case Queue")

df_cases = st.session_state.df_cases
if not df_cases.empty and "status" in df_cases.columns:
    # Group by status.
    status_counts = df_cases["status"].value_counts().reset_index()
    status_counts.columns = ["Status", "Count"]

    status_colors_map = {
        "open": "#2563eb",
        "l1_aml_analyst": "#2563eb",
        "l1_analyst": "#2563eb",
        "l2_investigator": "#7c3aed",
        "str_filing": "#dc2626",
        "sar_filing": "#dc2626",
        "edd_review": "#d97706",
        "closed_no_action": "#6b7280",
    }

    # Show status summary as colored cards.
    status_cols = st.columns(min(len(status_counts), 5))
    for i, row in status_counts.iterrows():
        with status_cols[i % len(status_cols)]:
            color = status_colors_map.get(row["Status"], "#6b7280")
            kpi_card(row["Status"].replace("_", " ").title(), int(row["Count"]), color)

    st.markdown("<br>", unsafe_allow_html=True)

    # Show open/active cases table.
    active = df_cases[~df_cases["status"].isin(["closed_no_action"])]
    if not active.empty:
        show_cols = ["case_id", "rule_id", "severity", "status"]
        if "queue" in active.columns:
            show_cols.insert(3, "queue")
        available = [c for c in show_cols if c in active.columns]

        def _status_color(val):
            c = status_colors_map.get(val, "")
            return f"color: {c}; font-weight: 700;" if c else ""

        styled = active[available].style.map(_status_color, subset=["status"])
        st.dataframe(styled, use_container_width=True, hide_index=True)

        # --- Bulk actions ---
        st.markdown("<br>", unsafe_allow_html=True)
        st.markdown("### Bulk Actions")
        open_cases = active[~active["status"].isin(["str_filing", "sar_filing"])]
        if not open_cases.empty:
            selected = st.multiselect(
                "Select cases",
                open_cases["case_id"].tolist(),
                help="Select cases for bulk action.",
            )
            if selected:
                col_b1, col_b2 = st.columns(2)
                with col_b1:
                    if st.button(
                        f"Bulk Close ({len(selected)})",
                        use_container_width=True,
                    ):
                        _bulk_action(selected, "closed", "closed_no_action")
                with col_b2:
                    if st.button(
                        f"Bulk Escalate ({len(selected)})",
                        use_container_width=True,
                        type="primary",
                    ):
                        _bulk_action(selected, "escalated", "l2_investigator")
    else:
        st.success("All cases resolved.")
else:
    st.caption("No cases in this run.")
