"""Emit dbt models + tests from an AML spec.

Banks running dbt-codegen pipelines can drop the output of `aml
generate-dbt` straight into their warehouse project. Each `custom_sql`
or `aggregation_window` rule becomes one dbt model under
`models/aml/<rule_id>.sql`; each `having` clause becomes a dbt
`tests/aml/<rule_id>_threshold.yml` schema test; `regulation_refs`
become the model's `description`. The output is a self-contained
package that dbt understands without modification.

Scope (this PR — the scaffold)
------------------------------
- `aggregation_window` rules → dbt model rendering the same SQL the
  reference engine generates for DuckDB. Vendor-specific dialect
  notes are TODO in the model header.
- `custom_sql` rules → dbt model with the inline SQL verbatim, with
  the spec's window placeholders substituted from `dbt_vars` so the
  rule is portable.
- `schema.yml` per rule documents the column types + the regulation
  refs.

What's NOT here (queued for Round 19)
-------------------------------------
- `python_ref` rules — these need a UDF surface (Snowflake Python
  UDFs, BigQuery remote functions). Out of scope for the scaffold.
- `list_match` / `network_pattern` — both need engine-side
  reference tables loaded into the warehouse before the dbt models
  can run. Listed as TODO in the README the generator emits.
- Macro library for the time-window helpers (`recent_start`,
  `baseline_start`). Currently each model gets the substitutions
  inlined; a macro layer would let operators tune windows
  globally.
"""

from __future__ import annotations

import re
from datetime import datetime, timedelta
from pathlib import Path

from aml_framework.spec.models import AMLSpec, Rule

# dbt model header. Stamped on every emitted .sql so a `dbt docs`
# viewer can answer "where did this model come from".
_MODEL_HEADER = """\
-- Generated by `aml generate-dbt` from {spec_path}
-- DO NOT EDIT — regenerate from the spec.
-- Rule: {rule_id} ({rule_name})
-- Severity: {severity}
-- Regulation refs:
{reg_refs_block}
{{{{
    config(
        materialized='table',
        tags=['aml', '{rule_id}']
    )
}}}}
"""


def _safe_identifier(s: str) -> str:
    """dbt model names must be `[a-z][a-z0-9_]*`. Strip non-word chars
    so a spec rule id like `structuring_cash_deposits` works as-is and
    a spec author who slips a hyphen in doesn't break dbt parse."""
    out = re.sub(r"[^a-z0-9_]", "_", s.lower())
    if not out or not out[0].isalpha():
        out = "aml_" + out
    return out


def _reg_refs_block(rule: Rule) -> str:
    if not rule.regulation_refs:
        return "--   (no regulation_refs declared)"
    return "\n".join(f"--   - {ref.citation}: {ref.description}" for ref in rule.regulation_refs)


def _render_window_placeholders(as_of: datetime) -> dict[str, str]:
    """Same placeholders the reference engine substitutes — kept as
    explicit dbt vars so an operator can override per-run without
    rebuilding the model. For dbt-codegen we substitute them inline
    by default."""
    return {
        "as_of": as_of.isoformat(sep=" "),
        "window_start": (as_of - timedelta(days=30)).isoformat(sep=" "),
        "recent_start": (as_of - timedelta(days=7)).isoformat(sep=" "),
        "baseline_start": (as_of - timedelta(days=37)).isoformat(sep=" "),
        "dormant_cutoff": (as_of - timedelta(days=45)).isoformat(sep=" "),
    }


def _render_custom_sql_model(rule: Rule, as_of: datetime, spec_path: Path) -> str:
    header = _MODEL_HEADER.format(
        spec_path=spec_path,
        rule_id=rule.id,
        rule_name=rule.name,
        severity=rule.severity,
        reg_refs_block=_reg_refs_block(rule),
    )
    sql_body = (rule.logic.sql or "").strip()
    for placeholder, value in _render_window_placeholders(as_of).items():
        sql_body = sql_body.replace(f"{{{placeholder}}}", value)
    return f"{header}\n{sql_body}\n"


def _render_aggregation_window_model(rule: Rule, as_of: datetime, spec_path: Path) -> str:
    """Inline an aggregation_window rule as dbt SQL by piggybacking on
    the reference SQL renderer. We strip the `-- rule_id` etc. header
    the engine renderer adds and replace with the dbt config block."""
    from aml_framework.generators.sql import compile_rule_sql

    engine_sql = compile_rule_sql(rule, as_of=as_of, source_table=rule.logic.source or "txn")
    # The engine's `_rule_header` prefixes the SQL with `-- rule_id:`
    # lines — strip those so the dbt model has clean SQL after our
    # own dbt-config header.
    cleaned = "\n".join(line for line in engine_sql.splitlines() if not line.startswith("-- "))
    header = _MODEL_HEADER.format(
        spec_path=spec_path,
        rule_id=rule.id,
        rule_name=rule.name,
        severity=rule.severity,
        reg_refs_block=_reg_refs_block(rule),
    )
    return f"{header}\n{cleaned.lstrip()}\n"


def _render_schema_yml(rule: Rule) -> str:
    """Per-model schema.yml — describes the columns the model emits
    and pins the having-clause thresholds as dbt schema tests."""
    description = f"{rule.name}. Severity: {rule.severity}."
    if rule.regulation_refs:
        description += " Regulation refs: " + "; ".join(
            f"{r.citation}" for r in rule.regulation_refs
        )
    lines = [
        "version: 2",
        "models:",
        f"  - name: {_safe_identifier(rule.id)}",
        "    description: |-",
        f"      {description}",
        "    columns:",
        "      - name: customer_id",
        "        description: Subject whose activity triggered the alert.",
        "        tests:",
        "          - not_null",
    ]
    # If the rule has a `count` or `sum_amount` aggregate, emit
    # type-checking tests.
    if getattr(rule.logic, "having", None):
        having = rule.logic.having
        for metric in ("count", "sum_amount"):
            if metric in having:
                lines.extend(
                    [
                        f"      - name: {metric}",
                        f"        description: Aggregated {metric} that triggered the alert.",
                        "        tests:",
                        "          - not_null",
                    ]
                )
    return "\n".join(lines) + "\n"


def generate_dbt_project(
    spec: AMLSpec,
    spec_path: Path,
    output_dir: Path,
    *,
    as_of: datetime | None = None,
) -> dict[str, Path]:
    """Emit dbt models + schema.yml + project skeleton.

    Returns a `{name: path}` map of every file written, so callers
    (CLI, tests) can verify the output set without re-walking the
    filesystem.

    The output layout:

        output_dir/
            dbt_project.yml
            models/aml/
                <rule_id>.sql       (one per aggregation_window /
                                     custom_sql rule)
                schema.yml          (one combined file with all
                                     model descriptions)
            README.md               (operator-facing notes)
    """
    if as_of is None:
        as_of = datetime.now().replace(microsecond=0)
    output_dir.mkdir(parents=True, exist_ok=True)
    models_dir = output_dir / "models" / "aml"
    models_dir.mkdir(parents=True, exist_ok=True)

    written: dict[str, Path] = {}

    # 1. dbt_project.yml — the minimum dbt needs to recognise the dir.
    project_yml = output_dir / "dbt_project.yml"
    project_yml.write_text(
        """\
name: 'aml_open_framework'
version: '1.0.0'
config-version: 2

profile: 'aml'

model-paths: ["models"]

models:
  aml_open_framework:
    aml:
      +materialized: table
      +tags: ['aml', 'generated']
""",
        encoding="utf-8",
    )
    written["dbt_project.yml"] = project_yml

    # 2. Per-rule .sql.
    schema_entries: list[str] = ["version: 2", "models:"]
    for rule in spec.rules:
        logic_type = getattr(rule.logic, "type", None)
        if logic_type == "custom_sql":
            sql = _render_custom_sql_model(rule, as_of, spec_path)
        elif logic_type == "aggregation_window":
            sql = _render_aggregation_window_model(rule, as_of, spec_path)
        else:
            # python_ref, list_match, network_pattern — skip with a
            # README note instead of emitting a broken model.
            continue
        model_name = _safe_identifier(rule.id)
        model_path = models_dir / f"{model_name}.sql"
        model_path.write_text(sql, encoding="utf-8")
        written[f"models/aml/{model_name}.sql"] = model_path
        # Build schema.yml entries inline so we emit one combined
        # file (matches dbt-codegen's preferred layout).
        per_model = _render_schema_yml(rule)
        # Strip the `version: 2\nmodels:` prefix from each per-model
        # block; we accumulate just the model entries.
        body = per_model.split("models:\n", 1)[1] if "models:" in per_model else per_model
        schema_entries.append(body.rstrip())

    schema_path = models_dir / "schema.yml"
    schema_path.write_text("\n".join(schema_entries) + "\n", encoding="utf-8")
    written["models/aml/schema.yml"] = schema_path

    # 3. README — what's covered, what's deferred.
    readme = output_dir / "README.md"
    readme.write_text(
        f"""\
# AML dbt project

Generated by `aml generate-dbt` from `{spec_path}`. Drop into your
warehouse's dbt project root and `dbt run --select tag:aml`.

## Covered

- `aggregation_window` rules compile to dbt models.
- `custom_sql` rules compile to dbt models with window placeholders
  substituted from the spec's `as_of`.
- Per-model `schema.yml` describes columns + carries `not_null`
  tests on `customer_id` + aggregate columns.

## Not covered (yet)

- `python_ref` rules: need a UDF surface (Snowflake Python UDFs,
  BigQuery remote functions). Add manually for now.
- `list_match` / `network_pattern` rules: need reference tables +
  graph relations in the warehouse. Operator wires those.
- Time-window helpers (`recent_start`, `baseline_start`) are
  inlined per-model. A macro layer for global tuning is queued for
  Round 19.

## Regeneration

This project is one-shot generated. Re-run `aml generate-dbt
<spec.yaml> -o <this_dir>` to refresh after spec changes — do NOT
hand-edit the `.sql` files, they're regenerated wholesale.
""",
        encoding="utf-8",
    )
    written["README.md"] = readme
    return written
