"""Auto-generate STR/SAR narrative text from case data.

Produces the who/what/when/where/why/how structure required by FINTRAC STR
and FinCEN SAR filing forms. The narrative is populated from the case alert
data, customer profile, and rule regulation references.
"""

from __future__ import annotations

from typing import Any


def generate_str_narrative(
    case: dict[str, Any],
    customer: dict[str, Any] | None,
    transactions: list[dict[str, Any]],
    jurisdiction: str = "CA",
) -> str:
    """Generate a structured STR/SAR narrative from case data."""
    alert = case.get("alert", {})
    rule_name = case.get("rule_name", case.get("rule_id", "Unknown"))
    severity = case.get("severity", "unknown")
    case_id = case.get("case_id", "N/A")
    queue = case.get("queue", "N/A")

    # Customer info.
    cust_name = customer.get("full_name", "Unknown") if customer else "Unknown"
    cust_id = customer.get("customer_id", "N/A") if customer else "N/A"
    cust_country = customer.get("country", "N/A") if customer else "N/A"
    cust_risk = customer.get("risk_rating", "N/A") if customer else "N/A"

    # Alert details.
    amount = alert.get("sum_amount", 0)
    txn_count = alert.get("count", "N/A")
    window_start = str(alert.get("window_start", "N/A"))[:10]
    window_end = str(alert.get("window_end", "N/A"))[:10]

    # Regulation references.
    refs = case.get("regulation_refs", [])
    ref_text = "; ".join(f"{r['citation']}" for r in refs) if refs else "N/A"

    # Transaction summary.
    txn_summary = ""
    if transactions:
        channels = {}
        for t in transactions:
            ch = t.get("channel", "unknown")
            channels[ch] = channels.get(ch, 0) + float(t.get("amount", 0))
        channel_lines = [f"  - {ch}: ${vol:,.2f}" for ch, vol in sorted(channels.items())]
        txn_summary = "\n".join(channel_lines)

    filing_type = "Suspicious Transaction Report (STR)" if jurisdiction == "CA" else "Suspicious Activity Report (SAR)"
    regulator = "FINTRAC" if jurisdiction == "CA" else "FinCEN"

    return f"""
{filing_type}
{'=' * len(filing_type)}
Generated by: AML Open Framework (automated draft — requires analyst review)
Case ID: {case_id}
Filing to: {regulator}

1. WHO (Subject of the Report)
   Name: {cust_name}
   Customer ID: {cust_id}
   Country: {cust_country}
   Risk Rating: {cust_risk}

2. WHAT (Description of Suspicious Activity)
   Detection Rule: {rule_name}
   Severity: {severity.upper()}
   Aggregate Amount: ${float(amount):,.2f}
   Transaction Count: {txn_count}

3. WHEN (Time Period)
   Activity Period: {window_start} to {window_end}
   Detection Date: {window_end}

4. WHERE (Location / Channel)
   Customer Jurisdiction: {cust_country}
   Transaction Channels:
{txn_summary or '   N/A'}

5. WHY (Reason for Suspicion)
   The above activity was flagged by automated detection rule "{rule_name}"
   (severity: {severity}). The pattern is consistent with indicators described
   in {ref_text}.

6. HOW (Method)
   The subject conducted {txn_count} transaction(s) totalling ${float(amount):,.2f}
   during the period {window_start} to {window_end}. The activity triggered
   the detection threshold and was escalated to queue "{queue}" for
   investigation.

Regulatory Citations: {ref_text}
Evidence Requested: {', '.join(case.get('evidence_requested', []))}

--- END OF AUTOMATED DRAFT ---
This narrative was auto-generated from case data and requires review by
a qualified analyst before filing with {regulator}.
""".strip()
